"""Model-free P3S decomposition, paired inference, and token-link analysis."""
from __future__ import annotations
import hashlib
from typing import Any
import numpy as np,pandas as pd
P2P_EFFECTS={'R1':.02000000806697237,'R2':.0017144594890368212,'R3':.01483719019840161,'R4':.02508755921050702}
def seed(label):return int.from_bytes(hashlib.sha256(f'FDCA-P3S-BOOTSTRAP|{label}'.encode()).digest()[:8],'big')
def boot(left,right,label,n=20000):
 ids=sorted(set(left)&set(right));l=np.array([left[i] for i in ids]);r=np.array([right[i] for i in ids]);d=l-r;rng=np.random.default_rng(seed(label));draw=d[rng.integers(0,len(d),(n,len(d)))].mean(1);lm=float(l.mean());rm=float(r.mean());return {'block_count':len(ids),'left_mean':lm,'right_mean':rm,'difference_mean':float(d.mean()),'ci95_lower':float(np.quantile(draw,.025,method='higher')),'ci95_upper':float(np.quantile(draw,.975,method='higher')),'ratio_of_block_means':lm/rm if rm else float('inf'),'positive_block_count':int((d>0).sum()),'bootstrap_resamples':n,'semantic_seed':seed(label)}
def decompose(rows,law):
 n=rows[rows.panel_type.eq('natural')].groupby(['panel','cfg_weight','block_id','anchor_target_rho'],as_index=False).agg(lpips_alex=('lpips_alex','mean'),dino_cosine_distance=('dino_cosine_distance','mean'),seed_count=('seed_count','mean'),severity_tv=('severity_tv','mean'),severity_surprisal=('severity_surprisal','mean'),connected_components=('connected_components','mean'),bounding_box_area=('bounding_box_area','mean'),D_desc_rate=('D_desc_rate','mean'),descendant_count=('descendant_count','mean'),first_descendant_step=('first_descendant_step','mean'),maximum_seed_to_descendant_radius=('maximum_seed_to_descendant_radius','mean'),descendant_connected_components=('descendant_connected_components','mean'),descendant_fraction_distance_le_5=('descendant_fraction_distance_le_5','mean'))
 keep=law[['panel','cfg_weight','block_id','anchor_target_rho','split_incidence','expected_seed_count','single_seed_probability','multi_seed_probability']];n=n.merge(keep,on=['panel','cfg_weight','block_id','anchor_target_rho'],validate='one_to_one');n['unconditional_lpips_alex']=n.split_incidence*n.lpips_alex;n['unconditional_dino_cosine_distance']=n.split_incidence*n.dino_cosine_distance;return n
def mp(frame,rho,col):return frame[frame.anchor_target_rho.eq(rho)].set_index('block_id')[col].to_dict()
def evaluate(rows,dec):
 p=dec[dec.panel.eq('primary_cfg3')];m=rows[(rows.panel.eq('primary_cfg3'))&rows.panel_type.eq('matched_timing')].groupby(['block_id','anchor_target_rho'],as_index=False).lpips_alex.mean();spec=[('R1',p,'lpips_alex','conditional_lpips'),('R2',p,'unconditional_lpips_alex','unconditional_lpips'),('R3',p,'dino_cosine_distance','conditional_dino'),('R4',m,'lpips_alex','matched_lpips')];out={}
 for key,f,col,label in spec:
  z=boot(mp(f,.5,col),mp(f,.3,col),label);z['pass']=z['ci95_lower']>0 and z['ratio_of_block_means']>=1.5;z['p2p_difference']=P2P_EFFECTS[key];z['effect_retention_ratio']=z['difference_mean']/P2P_EFFECTS[key];out[key]=z
 return out
def ridge(xtr,ytr,xte):
 mu=xtr.mean(0);sd=xtr.std(0);sd[sd<1e-12]=1;z=(xtr-mu)/sd;zt=(xte-mu)/sd;ym=ytr.mean();beta=np.linalg.solve(z.T@z+np.eye(z.shape[1]),z.T@(ytr-ym));return ym+zt@beta
def predictor(rows):
 f=rows[(rows.panel.eq('primary_cfg3'))&rows.panel_type.eq('natural')].copy().reset_index(drop=True);base=['seed_count','severity_tv','severity_surprisal','connected_components','bounding_box_area'];extra=['D_desc_rate','descendant_count','first_descendant_step','maximum_seed_to_descendant_radius','descendant_connected_components','descendant_fraction_distance_le_5'];x=f[base+extra].astype(float);x['first_descendant_step']=x.first_descendant_step.fillna(33);rho=(f.anchor_target_rho.eq(.5).astype(float).to_numpy()[:,None]);x0=np.column_stack([rho,x[base]]);x1=np.column_stack([rho,x[base+extra]]);y=f.lpips_alex.to_numpy(float);p0=np.empty(len(f));p1=np.empty(len(f));fold=[]
 for b in sorted(f.block_id.unique()):
  te=f.block_id.eq(b).to_numpy();tr=~te;p0[te]=ridge(x0[tr],y[tr],x0[te]);p1[te]=ridge(x1[tr],y[tr],x1[te]);fold.append({'heldout_block':b,'heldout_rows':int(te.sum()),'heldout_absent_from_train':b not in set(f.loc[tr,'block_id'])})
 f['prediction_S0']=p0;f['prediction_S1']=p1;f['abs_error_S0']=abs(y-p0);f['abs_error_S1']=abs(y-p1);f['propagation_contribution']=p1-p0;bm=f.groupby('block_id').agg(e0=('abs_error_S0','mean'),e1=('abs_error_S1','mean'));imp=(bm.e0-bm.e1).to_numpy();rng=np.random.default_rng(seed('TOKEN_MAE'));draw=imp[rng.integers(0,len(imp),(20000,len(imp)))].mean(1);f['rank_y']=f.groupby('anchor_target_rho').lpips_alex.rank();f['rank_c']=f.groupby('anchor_target_rho').propagation_contribution.rank();corr=float(f[['rank_y','rank_c']].corr().iloc[0,1]);bs=[]
 for _,g in f.groupby('block_id'):bs.append([len(g),g.rank_y.sum(),g.rank_c.sum(),(g.rank_y**2).sum(),(g.rank_c**2).sum(),(g.rank_y*g.rank_c).sum()])
 bs=np.array(bs);ix=np.random.default_rng(seed('TOKEN_SPEARMAN')).integers(0,len(bs),(20000,len(bs)));s=bs[ix].sum(1);num=s[:,5]-s[:,1]*s[:,2]/s[:,0];den=np.sqrt(np.maximum((s[:,3]-s[:,1]**2/s[:,0])*(s[:,4]-s[:,2]**2/s[:,0]),0));bc=np.divide(num,den,out=np.zeros(len(s)),where=den>0);res={'blocks':int(f.block_id.nunique()),'rows':len(f),'mae_S0':float(f.abs_error_S0.mean()),'mae_S1':float(f.abs_error_S1.mean()),'mae_ratio_S1_over_S0':float(f.abs_error_S1.mean()/f.abs_error_S0.mean()),'mae_improvement':float(imp.mean()),'mae_improvement_ci95_lower':float(np.quantile(draw,.025,method='higher')),'mae_improvement_ci95_upper':float(np.quantile(draw,.975,method='higher')),'within_rho_spearman':corr,'within_rho_spearman_ci95_lower':float(np.quantile(bc,.025,method='higher')),'within_rho_spearman_ci95_upper':float(np.quantile(bc,.975,method='higher')),'lobo_no_leakage':all(z['heldout_absent_from_train'] for z in fold)};res['replicated']=res['mae_ratio_S1_over_S0']<=.80 and res['mae_improvement_ci95_lower']>0 and res['within_rho_spearman']>.20 and res['within_rho_spearman_ci95_lower']>0;return f,pd.DataFrame(fold),res
